### ISSUE TITLE
TP06

### ISSUE THREAD

**Issue by emmanuel-lena** [srnfr/TP-CNI#15]
[TP06](https://github.com/srnfr/TP-CNI/blob/main/docs/TP06.md#bonus-cilium) Partie Bonus Cilium

Le commande
`kubectl -n kube-system exec -it ds/cilium -- cilium endpoint get -l k8s:role=leader` échoue avec le message 
![image](https://user-images.githubusercontent.com/50426668/190114584-278a2f90-d493-4d15-bc7e-0e9031662f63.png)
Tandis que la commande 
`kubectl -n kube-system exec -it ds/cilium -- cilium endpoint get -l k8s:role=follower` fonctionne normalement.
![image](https://user-images.githubusercontent.com/50426668/190114886-f79c1903-39a9-4e01-8890-07c8559777f9.png)

**Comment by srnfr** [comment]
C'est parce qu'il n'y a pas de Pod avec le label` role=leader `. Ce n'est nécessairement une erreur, juste une constatation
